version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - shared-data:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: "start-notebook.sh \
        --NotebookApp.password=${ACCESS_TOKEN}"
    restart: on-failure

  rstudio:
    image: rocker/geospatial
    ports:
      - "8787:8787"
    environment:
      - "PASSWORD=${PWD_VAR}"
      - "USER=${USERNAME}"
    volumes:
      - shared-data:/home/rstudio/shareddata
    restart: on-failure

volumes:
  shared-data:
